// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMYPslAsizHB3DSBNvJUXVmHU3g2tz5g',
    appId: '1:730594576128:web:5ae53fe41c42906d9e95e5',
    messagingSenderId: '730594576128',
    projectId: 'todos-a',
    authDomain: 'todos-a.firebaseapp.com',
    storageBucket: 'todos-a.appspot.com',
    measurementId: 'G-WHVJ0CGYBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxF9D_WwxmXf4Hzb4S28jGT8HYdBJFj9A',
    appId: '1:730594576128:android:09a8f0457e414f1d9e95e5',
    messagingSenderId: '730594576128',
    projectId: 'todos-a',
    storageBucket: 'todos-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXMxWKLOjG4elyjKp7PzEE9xPHtNyYuY',
    appId: '1:730594576128:ios:aa2af3523971ef359e95e5',
    messagingSenderId: '730594576128',
    projectId: 'todos-a',
    storageBucket: 'todos-a.appspot.com',
    androidClientId: '730594576128-84u3o19uainllbk6n2oknk06v60ua0g0.apps.googleusercontent.com',
    iosClientId: '730594576128-0mhb3jl7j66ppn3ihr4adiqu6168ukr2.apps.googleusercontent.com',
    iosBundleId: 'ntn.app.todos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHXMxWKLOjG4elyjKp7PzEE9xPHtNyYuY',
    appId: '1:730594576128:ios:aa2af3523971ef359e95e5',
    messagingSenderId: '730594576128',
    projectId: 'todos-a',
    storageBucket: 'todos-a.appspot.com',
    androidClientId: '730594576128-84u3o19uainllbk6n2oknk06v60ua0g0.apps.googleusercontent.com',
    iosClientId: '730594576128-0mhb3jl7j66ppn3ihr4adiqu6168ukr2.apps.googleusercontent.com',
    iosBundleId: 'ntn.app.todos',
  );
}
